package com.example.apppedido

import com.google.gson.annotations.SerializedName

class DCZona : ArrayList<DCZonaItem>()

data class DCZonaItem(
    val codigo: String,
    val estado: String,
    val fechaCreacion: String,
    val fechaModificacion: Any,
    val flagSys: String,
    val imagen1: Any,
    @SerializedName("nombre") val nombreZonas: String,
    @SerializedName("numero") val idZona: String,
    val referencia1: String,
    val referencia10: String,
    val referencia11: String,
    val referencia12: String,
    val referencia13: String,
    val referencia14: String,
    val referencia15: String,
    val referencia16: String,
    val referencia17: String,
    val referencia18: String,
    val referencia19: String,
    val referencia2: String,
    val referencia20: String,
    val referencia21: String,
    val referencia22: String,
    val referencia23: String,
    val referencia24: String,
    val referencia25: String,
    val referencia26: Any,
    val referencia27: Any,
    val referencia28: Any,
    val referencia29: Any,
    val referencia3: String,
    val referencia30: Any,
    val referencia31: Any,
    val referencia32: Any,
    val referencia33: Any,
    val referencia34: Any,
    val referencia35: Any,
    val referencia4: String,
    val referencia5: String,
    val referencia6: String,
    val referencia7: String,
    val referencia8: String,
    val referencia9: String,
    val tabla: Any,
    val usuarioCreacion: String,
    val usuarioModificacion: Any
)